# Generated by Django 5.0 on 2023-12-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expart_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
