# Generated by Django 5.0 on 2023-12-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='iconLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
