# Generated by Django 5.0 on 2023-12-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_service_iconlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servicesection',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='app.ipmodel'),
        ),
    ]
